name: DP-AfkShop
version: 1.0.0.2
main: com.blueearthcat.dpas.AfkShop
api-version: 1.14
authors: [ BlueEarthCat ]
depend:
  - DPP-Core
  - PlaceholderAPI
  - WorldGuard
commands:
  dpafk:
    aliases: [ afk ]
  dpafkshop:
    aliases: [ afkshop ]